#!/bin/sh

#[Linux] $ ln Scripts/hooks/pre-push .git/hooks
#[Windows Powershell] New-Item -Type SymbolicLink .git/hooks/pre-push -Value Scripts/hooks/pre-push

remote="$1"
url="$2"
 
z40=0000000000000000000000000000000000000000
 
while read local_ref local_sha remote_ref remote_sha
do
	if [[ "${remote_ref##refs/heads/}" = "develop" ]]; then
		`git rev-parse --show-toplevel`/Scripts/convert.sh
		git checkout master
		git checkout develop `git rev-parse --show-toplevel`'/EyeTracking/*.fbx'
		git checkout develop `git rev-parse --show-toplevel`'/EyeTracking/Textures/*'
        git checkout develop `git rev-parse --show-toplevel`'/GrassVR/*.fbx'
		git checkout develop `git rev-parse --show-toplevel`'/GrassVR/Textures/*'
        #git checkout develop `git rev-parse --show-toplevel`'/EscapeVR/*.fbx'
		#git checkout develop `git rev-parse --show-toplevel`'/EscapeVR/Textures/*'
		git commit -m "[Auto commit] Add FBX from develop(rinadehi/3DAssets-All)"

		cd  `git rev-parse --show-toplevel`
		cp -r GrassVR/*.fbx  ../Unity-GrassVR/GrassVR/Assets/3DAssets/
		cp -r GrassVR/Textures/*  ../Unity-GrassVR/GrassVR/Assets/3DAssets/Textures/

		git checkout develop
		git push OnlyFBX master
	fi
done
