#!/bin/sh

# $ ln -s  Scripts/hooks/pre-push .git/hooks

remote="$1"
url="$2"
 
z40=0000000000000000000000000000000000000000
 
while read local_ref local_sha remote_ref remote_sha
do
	if [[ "${remote_ref##refs/heads/}" = "develop" ]]; then
		#`git rev-parse --show-toplevel`/Scripts/convert.sh
		git checkout master
		git checkout develop '`git rev-parse --show-toplevel`/EyeTracking/*.fbx'
        git checkout develop '`git rev-parse --show-toplevel`/GrassVR/*.fbx'
        git checkout develop '`git rev-parse --show-toplevel`/EscapeVR/*.fbx'
		git commit -m "[Auto commit] Add FBX from develop(rinadehi/3DAssets-All)"
		git checkout develop
		git push OnlyFBX master
	fi
done